### ISSUE TITLE
Inline linting on save

### ISSUE THREAD

**Issue by simenbrekken** [fbzhong/sublime-closure-linter#2]
Similar to [SublimeLinter](https://github.com/Kronuz/SublimeLinter), would it be possible to run the linter on save and have the results?

**Comment by fbzhong** [comment]
Actually I do implement such feature in https://github.com/fbzhong/sublime-jslint .

Let me merge the feature to this.

**Comment by gabbon** [comment]
While waiting for a fix for this I tried to implement it myself in my local listener.py but keep getting 3 results on on_post_save. Any idea why this is?
Here's what I did:
sublime.active_window().run_command("closure_linter")
only it runs 3 times instead of the expected one.
